```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(latex2exp)
library(gridExtra)
library(lmtest)
library(stargazer)
library(car)
library(GGally)
library(multcomp)
library(dplyr)
library(fixest)
library(latex2exp)
library(kableExtra)
library(modelsummary)
library(sandwich)
```

```{r}
setwd("..")
df <- read_csv('airline.csv', show_col_types = FALSE)
colnames(df)[colnames(df) == "On-board_service"] <- "On_board_service"
```

```{r}
#Baggage_handling, Age_group, Leg_room_service, Online_boarding, Ease_of_Online_booking, Flight_haul
#не значущі
df$Cleanliness <- as.factor(df$Cleanliness)
df$Inflight_service <- as.factor(df$Inflight_service)
df$Checkin_service <- as.factor(df$Checkin_service)
df$On_board_service <- as.factor(df$`On_board_service`)
df$Inflight_entertainment <- as.factor(df$Inflight_entertainment)
df$Seat_comfort <- as.factor(df$Seat_comfort)
df$Food_and_drink <- as.factor(df$Food_and_drink)
df$Inflight_wifi_service <- as.factor(df$Inflight_wifi_service)

#не дуже значущі
df$Age_group <- as.factor(df$Age_group)

#значущі
df$Baggage_handling <- as.factor(df$Baggage_handling)
df$Leg_room_service <- as.factor(df$Leg_room_service)
df$Online_boarding <- as.factor(df$Online_boarding)
df$Ease_of_Online_booking <- as.factor(df$Ease_of_Online_booking)
```

```{r}
print('_____________________________')
model1 <- feols(Satisfaction ~ Online_boarding * Ease_of_Online_booking  + Inflight_service + On_board_service + I(log(Age)) + Flight_Distance | Gender, data = df)
ci <- coefci(model1)

modelsummary(model1,
             stars = TRUE,
             output = "output_business/clustering.html",
             gof_omit = "^(?!Num.Obs.|R2 Adj.)")|>
  kable_styling(font_size = 15)
``










